apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-scanner
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: false
    model: gpt-5.2-codex
    backend: openai
  noCache: false
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.4.27
